basic_settings:
  db:
  - local: enable
    url: /root/twikoo/data/db.json.0
  - mongodb: disable
    url: mongodb://localhost:27017
  port: 3000
  debug: true
  cors: true
  password: 
  JWT_SECRET_KEY: 
fentch_time:
  fentch_interval: 30
  dangerous_interval: 24
  failed_interval: 6
feishu:
  enable: false
  app_id:
  app_secret:
  encrypt:
mail:
  enable: false
  sender_email:
  smtp_host:
  smtp_port: 465
  smtp_secure: true
  smtp_user:
  smtp_pass:
